version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=users
    ports:
      - 27017:27017
    command: -smallfiles